# AGNI configuration file
title = "TRAPPIST-1 b, NO ATM"

[planet]
    tmp_surf        = 500.0
    instellation    = 5700
    albedo_b        = 0.0
    s0_fact         = 0.7
    zenith_angle    = 67
    surface_material= "greybody"
    albedo_s        = 0.0
    mass            = 8.21e24
    radius          = 7.11e6
    flux_int        = 0.0
    star_Teff       = 2566

[files]
    input_sf        = "res/spectral_files/Dayspring/256/Dayspring.sf"
    input_star      = "res/stellar_spectra/trappist-1.txt"
    output_dir      = "out/"

[composition]
    transparent     = true

[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 200
    max_runtime     = 400
    num_levels      = 50
    solution_type   = 3
    solver          = "transparent"
    dx_max          = 300.0
    initial_state   = ["iso", "500"]
    linesearch      = 2
    easy_start      = false
    grey_start      = false
    converge_atol   = 1e-1
    converge_rtol   = 1.0e-3
    perturb_all     = false

[physics]
    chemistry       = false
    continua        = true
    rayleigh        = false
    cloud           = false
    overlap_method  = "ee"
    real_gas        = true
    thermo_funct    = true
    sensible_heat   = true
    advection       = false
    conduction      = true
    latent_heat     = false
    convection      = true
    convection_crit = "s"
    rainout         = false
    oceans          = false

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = false
    height          = false
    cloud           = false
